### PR TITLE
Fix Xcode warnings for Swift 4.2 bump

### PR DESCRIPTION
**Pull request by dai-cb**

### CODE REVIEW

**Comment by dai-cb** [comment]
Tests failing on Build framework(swift 4.1)

**Comment by SCENEE** [comment]
FloatingPanel(1.3.2) supports both of  Swift 4.2 and 4.1. What's your problem??

**Comment by dai-cb** [comment]
When I updated to 1.3.2, XCode gave me all the warnings here https://github.com/SCENEE/FloatingPanel/pull/111/commits/42dfd2cc49fae0c77e5ea12c3130ec7befe8d517

**Comment by SCENEE** [comment]
The reason why the errors occur can be because "Swift 4.2" is set to "Swift Language Version" in "Build Settings" in your FloatingPanel's project. 
If you use CocoaPods, please try to recreate Pods.project by `pod deintegrate; pod install`.

**Comment by Elshad** [comment]
But `parent.addChildViewController(self)` is not swift 4.2 code. It seems we must compile `FloatingPanel` with swift 4.1 and then use in swift 4.2 project

**Comment by SCENEE** [comment]
> This conflicts with Readme's FloatingPanel is written in Swift 4.2

I'm sorry I forgot to modify the sentence. I will fix it.

I don't know why it is necessary to modify the library code because Swift 4.2 is compatible with Swift 4, Swift 4.1 and Swift 3. https://swift.org/blog/swift-4-2-released/ 

Actually, the "Samples" app is written in Swift 4.2. https://github.com/SCENEE/FloatingPanel/blob/master/Examples/Samples/Samples.xcodeproj/project.pbxproj#L502

**Comment by SCENEE** [comment]
I close this issue. I'm sorry the readme was confusing.

**Pull request closed without merging**
