### PR TITLE
Add support for specifying swift_versions in CocoaPods 1.7 and above

### PR DESCRIPTION
**Pull request by joshuafinch**

### CODE REVIEW

**Comment by joshuafinch** [comment]
Looks like travis-ci is still using a prior version of CocoaPods when running the build (and not the latest stable).

We could either update the `.travis.yml` to install the latest CocoaPods with a before step: `gem install cocoapods`, or add a `Gemfile` to the project that can lock the CocoaPods version with Bundler?

Unsure of the backwards compatibility of this change, for users that remain on CocoaPods 1.6.

**Comment by joshuafinch** [comment]
Have updated the `.travis.yml` to update CocoaPods to the latest version before running the `pod spec lint`, `pod lib lint` commands.

Have also double-checked the backwards compatibility of this change.
For users that remain on version 1.6 (or prior) version of CocoaPods, this is considered a breaking change as it will fail to install the pod.

Tried using variants of `swift_version`, and `swift_versions` with single (and array) version specifiers but couldn't find anything that was backwards compatible.

However, moving across to using `swift_versions` with the array based version specifiers will allow end-users of the Pod to be able to compile it with Swift 5.0 instead of Swift 4.0 by default.

**Comment by joshuafinch** [comment]
Looks like travis-ci is failing the build due to a warning in one of the swift files (from the 1.5.1 tag), when compiled with Swift 5.

If we were to update the `Podfile` to point at the new `1.6.0` release tag, then this should pass on travis-ci. But would depend on if how you want to manage that with the #213 PR as well.

**Comment by SCENEE** [comment]
I've run a build for this PR again on travis ci.

**Comment by SCENEE** [comment]
I'm planning to release this on v1.7.0. Thanks, @joshuafinch 👍

**Comment by SCENEE** [comment]
I'm sorry for late. I merged this PR to master for v1.7.0! Thank you.

**Pull request merged**
