### PR TITLE
Add FloatingPanelAdaptiveLayoutAnchor

### LINKED ISSUE #357: Make a panel height be dependant on the panel's scrollview contentView?
I'm building an app where I need to show a bottom panel like this:

Screen Shot 2020-05-21 at 11 18 37

This bottom sheet is its own view controller and uses a collectionview since there are a variable number of cells. I am not sure how to make FloatingPanel show this panel "as big as is needed". Using `FloatingPanelIntrinsicLayout` doesn't work, since the collectionview doesn't have an intrinsic height that's set by its cells. So for now I am using a fullscreen layout.

Code is something like this:

``` swift
class SpecialRequestsCoordinator {
  private let floatingPanelController = FloatingPanelController()
  private let rootViewController = SpecialRequestsViewController()

  init() {
    floatingPanelController.delegate = self
    floatingPanelController.isRemovalInteractionEnabled = true
    floatingPanelController.surfaceView.cornerRadius = 15
  }

  func openCatering() {
    let vc = SpecialRequestChoiceSelectViewController()
    floatingPanelController.set(contentViewController: vc)
    rootViewController.present(floatingPanelController, animated: true, completion: nil)
  }
}

extension SpecialRequestsCoordinator: FloatingPanelControllerDelegate {
  func floatingPanel(_ vc: FloatingPanelController, layoutFor newCollection: UITraitCollection) -> FloatingPanelLayout? {
    if vc.contentViewController is SpecialRequestChoiceSelectViewController {
      return FullLayout()
    }

    return IntrinsicLayout()
  }
}

class FullLayout: FloatingPanelLayout {
  func insetFor(position: FloatingPanelPosition) -> CGFloat? {
    switch position {
    case .full: return 0
    default: return nil
    }
  }

  var initialPosition: FloatingPanelPosition {
    return .full
  }

  var supportedPositions: Set<FloatingPanelPosition> {
    return [.full]
  }
}

class IntrinsicLayout: FloatingPanelIntrinsicLayout {
  func insetFor(position: FloatingPanelPosition) -> CGFloat? {
    return nil
  }

  public var initialPosition: FloatingPanelPosition {
    return .full
  }

  public var supportedPositions: Set<FloatingPanelPosition> {
    return [.full]
  }
}
```

And as you might expect, it is now shown like this, which is not ideal. It's way too big and empty:

Screen Shot 2020-05-21 at 11 22 19

So how can I configure FloatingPanel to show the panel only as big as a scrollview's `contentSize`? Alternatively I could look into calculating the height in the view controller and pass that into a custom fixed height layout class, but that's going to be a nightmare when taking dynamic type into consideration.

As an aside, it feels like the different `FloatingPanelLayout` protocols (FloatingPanelLayout, FloatingPanelIntrinsicLayout) are quite complicated. If you simply want a fixed height layout, or a 100% fullscreen layout as in my example above, there is so much repeated code.

### PR DESCRIPTION
**Pull request by SCENEE**
Resolve #357

### CODE REVIEW

**Comment by warpling** [comment]
Looking forward to this one!

**Comment by warpling** [comment]
I tested this branch with some views and got stuck in some layout loops >_< Is there a trick?

**Comment by keithZumper** [comment]
Looking forward to this one!

**Comment by SCENEE** [comment]
> I tested this branch with some views and got stuck in some layout loops >_< Is there a trick?

Thank you for your try! Could your give me a sample code to repro your problem? I would like to investigate and fix it 👍.

**Comment by warpling** [comment]
> > I tested this branch with some views and got stuck in some layout loops >_< Is there a trick?
> 
> @warpling Thank you for your try! Could your give me a sample code to repro your problem? I would like to investigate and fix it 👍.

Sorry I quickly removed it and moved back to my custom solution of updating the Layout object after my childVC lays out it subviews but am happy to drop it into my project and try it again if you think it's more ready!

**Comment by SCENEE** [comment]
Thank you, @warpling. 784da8d is ready to merge, I think! Could you please try it again?

**Comment by warpling** [comment]
I'm unable to checkout this branch or commit with SPM. Any idea why?
image

**Comment by warpling** [comment]
Okay I got it working but all of my panels collapse to about 0 height.

**Comment by warpling** [comment]
image
It appears the view is sized very small (should be 2-3x taller) and is offscreen.

**Comment by warpling** [comment]
Apparently setting the panel's `contentMode` to `.fitToBounds` makes it work! I previously had never used this property and am still a bit confused what it does.

**Comment by SCENEE** [comment]
@warpling Thank you for your feedback.

> The behavior I'm seeing is still problematic though… for instance my views have content above and below the scrollView so the scrollView's contentLayoutGuide isn't an accurate representation of the full size.

`FloatingPanelAdaptiveLayoutAnchor` uses contentLayoutGuide to determine a panel location for each state and its size if its `contentMode` is  `static`. That is why, as you mentioned, the anchor won't show the entire content.

According to your other comment, of course I can't understand your app condition by them, but I figured out a problem of the current implementation, which is not able to follow content size changes. So I've pushed additional commits to fix it. I hope these would ease your problem.

**Comment by warpling** [comment]
This is pretty fantastic. Once I realized and remembered what `UILayoutGuide` actually was and that I could *create my own and size them with AutoLayout* everything fell more or less into place. I'd say this looks pretty good to merge! It would be excellent to show an example of how you can provide your own `UILayoutGuide` in case you have something more complex than a simple UIScrollView that takes up the whole panel but make this PR and comment will serve to help in the future too ;)

**Comment by SCENEE** [comment]
@warpling Thank you so much for your feedback! I think so too. I could notice that by your above comment. So I've added an example using a custom layout guide on "Show Adaptive Panel(Custom Layout Guide)" 😉  I'm going to merge this in the next week and then release v2.1.0.

**Comment by warpling** [comment]
Nice work! Excited to integrate it.

**Comment by warpling** [comment]
Still need's a version bump :)

**Pull request merged**
