### PR TITLE
track scroll view bouncing

### PR DESCRIPTION
**Pull request by brightsider**
Released only for the bottom position. Maybe you have a better solution that already has been implemented? Trying to find, but can't.

Before
https://user-images.githubusercontent.com/4996231/149289842-37a3db3f-90ff-4f3d-b983-9a11a52c392f.mp4

After
https://user-images.githubusercontent.com/4996231/149289857-0665b24e-6c03-4feb-b12f-29943508b7bc.mp4

### CODE REVIEW

**Comment by scenee** [comment]
It looks a cool behavior! Thank you so much. I will check more details later to merge this to the main line.

**Comment by cjheinze** [comment]
This looks really nice! Hope this makes it!

**Comment by Jamonek** [comment]
Any updates here? Thank you both

**Comment by scenee** [comment]
Thank you for your patience. I’ve merged this PR. I’m going to release this feature in the next release.

**Pull request merged**
